<link href="https://fonts.googleapis.com/css?family=Roboto|Syncopate:700&display=swap" rel="stylesheet">
<link href="/index.php/assets?file=css/styles.css" rel="stylesheet" />

<h1 class="main-title">Room 1</h1>
<div class="dashboard">
    <div class="panel light">
        <div class="title">Light</div>
        <div class="values">
            <div class="value">
            <?php if ($this->arrays->getValueDotted($this->data, 'light.data.intensity') > 200): ?>
                <div class="value light-on">
                    ON
                </div>
            <?php else: ?>
                <div class="value light-off">
                OFF
                </div>
            <?php endif ?>
            </div>
        </div>
    </div>
    <div class="panel DHT">
        <div class="title">Inside</div>
        <div class="values">
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.data.temperature') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.metadata.units.temperature') ?>
                </div>
            </div>
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.data.humidity') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.metadata.units.humidity') ?>
                </div>
            </div>
        </div>
    </div>
    <div class="panel dallas">
        <div class="title">Outside</div>
        <div class="values">
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dallas.data.temperature') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dallas.metadata.units.temperature') ?>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="graphs">
    <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1020028/charts/2?bgcolor=%23ffffff&color=%23f56342&dynamic=true&results=60&title=IN+Temperature&type=line&yaxis=%C2%B0C"></iframe>
    <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1020028/charts/3?bgcolor=%23ffffff&color=%2342cbf5&dynamic=true&results=60&title=IN+Humidity&type=line&yaxis=%25"></iframe>
    <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1020028/charts/1?average=10&bgcolor=%23ffffff&color=%23f5bf42&dynamic=true&results=60&title=IN+Luminosity&type=step&yaxis=lux"></iframe>
    <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1020028/charts/4?bgcolor=%23ffffff&color=%23f56342&dynamic=true&results=60&title=OUT+Temperature&type=line&yaxis=%C2%B0C"></iframe>
</div>

<script type="text/javascript">
setTimeout(function () {
    // window.location.reload();
}, 5000);
</script>