<link href="https://fonts.googleapis.com/css?family=Roboto|Syncopate:700&display=swap" rel="stylesheet">
<link href="/index.php/assets?file=css/styles.css" rel="stylesheet" />

<h1 class="main-title">Room 1</h1>
<div class="dashboard">
    <div class="panel light">
        <div class="title">Light</div>
        <div class="values">
            <div class="value">
            <?php if ($this->arrays->getValueDotted($this->data, 'light.data.intensity') > 200): ?>
                <div class="value light-on">
                    ON
                </div>
            <?php else: ?>
                <div class="value light-off">
                OFF
                </div>
            <?php endif ?>
            </div>
        </div>
    </div>
    <div class="panel DHT">
        <div class="title">Inside</div>
        <div class="values">
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.data.temperature') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.metadata.units.temperature') ?>
                </div>
            </div>
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.data.humidity') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.metadata.units.humidity') ?>
                </div>
            </div>
<!--
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.data.heatIndex') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dht.metadata.units.heatIndex') ?>
                </div>
            </div>
-->
        </div>
    </div>
    <div class="panel dallas">
        <div class="title">Outside</div>
        <div class="values">
            <div class="value">
                <div class="value">
                    <?= $this->arrays->getValueDotted($this->data, 'dallas.data.temperature') ?>
                </div>
                <div class="label">
                    <?= $this->arrays->getValueDotted($this->data, 'dallas.metadata.units.temperature') ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
setTimeout(function () {
    // window.location.reload();
}, 5000);
</script>